version: "3.3"

networks:
  dinotopia:

services:
  app:
    build:
      context: ./.docker/nginx
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: dinotopia_app
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
      - db
    networks:
      - dinotopia

  php:
    build:
      context: ./.docker/php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: dinotopia_php
    volumes:
      - .:/var/www/html
    networks:
      - dinotopia

  db:
    image: mariadb:10.6
    container_name: dinotopia_db
    restart: unless-stopped
    tty: true
    volumes:
      - symfony_db:/var/lib/mysql
    ports:
      - "33069:3306"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - dinotopia

volumes:
  symfony_db:



